export const BODY = document.querySelector('body')
export const FILTER = document.createElement('div')
export const START_TITLE = document.createElement('p')
export const HEADER = document.createElement('header')
export const HEADER_TITLE = document.createElement('h1')
export const MAIN = document.createElement('main')
export const SECTION_TEXT_AREA = document.createElement('section')
export const SECTION_TEXT_AREA_WRAPPER = document.createElement('div')
export const TEXT_AREA = document.createElement('textarea')
export const SECTION_KEYBOARD = document.createElement('section')
export const SECTION_KEYBOARD_WRAPPER = document.createElement('div')
export const LEFT_BLOCK_SECTION_KEYBOARD = document.createElement('div')
export const P_OS = document.createElement('p')
export const P_LANG = document.createElement('p')
export const KEY_CONTAINER = document.createElement('div')
export const RIGHT_BLOCK_SECTION_KEYBOARD = document.createElement('div')
export const FOOTER = document.createElement('footer')
export const keyRowArr = [
  document.createElement('div'),
  document.createElement('div'),
  document.createElement('div'),
  document.createElement('div'),
  document.createElement('div')
]
keyRowArr.map((x) => x.classList.add('key-row'))
export function createDOM() {
  TEXT_AREA.setAttribute('cols', '45')
  TEXT_AREA.setAttribute('rows', '11')
  TEXT_AREA.id = 'textarea'
  BODY.classList.add('body')
  FILTER.classList.add('filter')
  BODY.appendChild(FILTER)
  START_TITLE.classList.add('start-title')
  START_TITLE.innerText = 'Click to start'
  FILTER.appendChild(START_TITLE)
  HEADER.classList.add('header')
  BODY.appendChild(HEADER)
  HEADER_TITLE.classList.add('header__title')
  HEADER_TITLE.innerText = '     '
  HEADER.appendChild(HEADER_TITLE)
  MAIN.classList.add('main')
  BODY.appendChild(MAIN)
  SECTION_TEXT_AREA.classList.add('text-area')
  MAIN.appendChild(SECTION_TEXT_AREA)
  SECTION_TEXT_AREA_WRAPPER.classList.add('wrapper')
  SECTION_TEXT_AREA.appendChild(SECTION_TEXT_AREA_WRAPPER)
  TEXT_AREA.classList.add('text-area__text-area')
  SECTION_TEXT_AREA_WRAPPER.appendChild(TEXT_AREA)
  SECTION_KEYBOARD.classList.add('keyboard')
  MAIN.appendChild(SECTION_KEYBOARD)
  SECTION_KEYBOARD_WRAPPER.classList.add('wrapper')
  SECTION_KEYBOARD.appendChild(SECTION_KEYBOARD_WRAPPER)
  LEFT_BLOCK_SECTION_KEYBOARD.classList.add('left-block-keyboard')
  SECTION_KEYBOARD_WRAPPER.appendChild(LEFT_BLOCK_SECTION_KEYBOARD)
  P_OS.classList.add('p-os')
  P_LANG.classList.add('p-lang')
  LEFT_BLOCK_SECTION_KEYBOARD.appendChild(P_OS)
  LEFT_BLOCK_SECTION_KEYBOARD.appendChild(P_LANG)
  KEY_CONTAINER.classList.add('key-container')
  SECTION_KEYBOARD_WRAPPER.appendChild(KEY_CONTAINER)
  RIGHT_BLOCK_SECTION_KEYBOARD.classList.add('right-block-keyboard')
  SECTION_KEYBOARD_WRAPPER.appendChild(RIGHT_BLOCK_SECTION_KEYBOARD)
  FOOTER.classList.add('footer')
  BODY.appendChild(FOOTER)
  TEXT_AREA.focus()
}